/*
-- Query: SELECT * FROM cion_db.`doctor inf`
LIMIT 0, 1000

-- Date: 2024-04-05 11:19
*/
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (1,'Dr. Muralidhar Muddusetty','Male','18+ years','Hyderabad','On call','Surgical Oncology','Senior Consultant','Dr. Muralidhar Muddusetty1687240344-Dr Murali.jpg','dr_muralidhar','Surgical Oncology','MRCS - Edinburgh','','',7,1,'2023-03-17 10:24:40','2023-07-04 14:52:13');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (2,'Dr. Raghunadha Rao','Male','45+ years','Vizag','On call','Medical Oncology','Advisor','Dr. Raghunadharao1687240892-Dr. ragunandanrao.jpg','raghunadharao','Senior Clinical advisor & Senior Consultant Medical Oncologist','DM Medical Oncology','','',14,1,'2023-03-17 10:24:40','2023-08-04 11:07:11');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (3,'Dr. Purushotham Reddy K','Male','7+ years','Hyderabad','10AM - 5PM','Surgical Oncology','Consultant','Dr. Purushotham Reddy K1687240295-Dr. Purusotham.jpg','purushotham-reddy','CONSULTANT - SURGICAL ONCOLOGY','M. Ch. Surgical Oncology','','',2,1,'2023-03-17 10:24:40','2023-07-04 14:52:27');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (4,'Dr. Kirti Ranjan Mohanty','Male','10+ years','Hyderabad','2PM - 5PM','Radiation Oncology','Senior Consultant','Dr. Kirti Ranjan Mohanty1687240529-Dr. Kiriti rajan mohanty.jpg','kirti-ranjan-mohanty','Senior Consultant - Radiation oncology','MD Radiation Oncology','','',9,1,'2023-03-17 10:24:40','2023-07-04 15:13:15');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (5,'Dr. Sushma P Venkata','Female','15+ years','Vizag','2PM - 5PM','Radiation Oncology','Senior Consultant','Dr. Venkata Sushma1687240495-Dr. Sushma.jpg','venkata-sushma','Senior Consultant - Radiation Oncology, Women’s Oncology, Neuro Oncology','MD Radiation Oncology','','',8,1,'2023-03-17 10:24:40','2023-07-04 15:13:31');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (6,'Dr. Gangadhar Vajrala','Male','10+ years','Hyderabad','2PM - 5PM','Radiation Oncology','Senior Consultant','Dr. Gangadhar Vajrala1687240568-Dr. Gangadhar.jpg','gangadhar-vajrala','Senior Consultant - Radiation oncology','MD Radiation Oncology','','',10,1,'2023-03-17 10:24:40','2023-07-04 15:13:49');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (7,'Dr. Naresh Gundu','Male','7+ years','Hyderabad','10AM - 5PM','Medical Oncology','Consultant','Dr. Gundu Naresh1687240282-Dr. Gundu Naresh.jpg','gundu-naresh','Consultant Medical Oncologist and Hematologist','DM Medical Oncology - AIIMS Delhi','','',1,1,'2023-03-17 10:24:40','2023-07-04 14:14:00');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (8,'DR. SARITA SHRIVASTVA','Female','7+ years','Hyderabad','10AM - 5PM','Medical Oncology','Consultant','3_sarita.jpg','None','Medical oncology','DM Medical Oncology - NIMS Hyderabad','','',3,0,'2023-03-17 10:24:40','2023-03-17 10:24:40');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (9,'Dr. Nagarjuna Chakravarthy','Male','15+ years','Hyderabad','On call','Anaesthesiology','Advisor','Dr. Nagarjuna Chakravarthy1687241075-Untitled design (10).png','nagarjuna-chakravarthy','Anaesthesiology, Critical Care and Palliative Medicine','DNB','','',15,1,'2023-03-17 10:24:40','2023-07-04 15:15:53');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (10,'Dr. Mahendra Parage','Male','25+ years','Hyderabad','10AM - 5PM','Pathology','Advisor','Dr. Mahendra Parage1687241062-Untitled design (9).png','mahendra-parage','Pathology','MD Pathology','','',16,1,'2023-03-17 10:24:40','2023-07-04 15:16:04');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (11,'Dr. Sasi Prabha Rokkam','Female','50+ years','Vizag','10AM - 5PM','Gynaecology','Advisor','Dr. Sasi Prabha Rokkam1687240953-Dr. Sasi Prabha.jpg','sasi-prabha-rokkam','Obstetrics and Gynaecology','MBBS MD DGO','','',18,1,'2023-03-17 10:24:40','2023-08-04 11:09:27');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (12,'Dr. Mahati Chittem','Female','11+ years','Hyderabad','On Call','Onco-Psychology','Supportive Care Specialist','Dr. Mahati Chittem1687240916-Dr. Mahati.jpg','mahati-chittem','Psycho-oncology, Health Psychology, Medical Psychology','PHD Health Psychology','','',20,1,'2023-03-17 10:24:40','2023-08-04 11:09:38');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (13,'Vasudha Mathur','Female','20+ years','Hyderabad','10AM - 5PM','Onco-Nutrition','Supportive Care Specialist','Vasudha Mathur1687240930-Dr. Vasudha.jpg','vasudha-mathur','Nutrition and Dietetics','Post Graduate Diploma','','',21,1,'2023-03-17 10:24:40','2023-08-04 11:09:52');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (14,'Dr. Srinivasulu Putcha Reddy','Male','13+ years','Vizag','10AM - 5PM','Radiation Oncology','Consultant','Dr. Srinivasulu Reddy Putcha1687240581-Dr. Srinivasulu.jpg','srinivasulu-reddy-putcha','CONSULTANT - RADIATION ONCOLOGY','MD Radiation Oncology','','',11,1,'2023-03-17 10:24:40','2023-07-04 15:14:07');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (15,'Dr. Imaduddin Mohammed','Male','6+ years','Hyderabad','10AM - 5PM','Surgical Oncology','Consultant','Dr. Mohammed Imaduddin1687240309-Dr. Imad.jpg','mohammed-imaduddin','Consultant, Surgical Oncology','M. Ch. Surgical Oncology','','',4,1,'2023-03-17 10:24:40','2023-07-04 14:54:11');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (16,'Dr. Raghavendra Reddy','Male','6+ years','Hyderabad','10AM - 5PM','Medical Oncology','Consultant','Dr. C Raghavendra Reddy1687240320-Dr. Raghavendra.jpg','ragavendra-reddy','Consultant Medical Oncologist','DM Medical Oncology - Gold Medal','','',5,1,'2023-03-17 10:24:40','2023-07-04 14:14:38');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (17,'Dr. Bharati Devi Gorantla','Female','7+ years','Vizag','10AM - 5PM','Medical Oncology','Consultant','Dr. Bharati Devi Gorantla1687240331-Dr. Bharathi Devi.jpg','bharati-devi-gorantla','Consultant Medical Oncologist','DM Medical Oncology','','',6,1,'2023-03-17 10:24:40','2023-07-04 14:14:56');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (22,'Dr. Srinivasulu Mukta','Male','35+ years','Hyderabad','10AM - 5PM','Surgical Oncology','Advisor','Dr. Srinivasulu Mukta1687240943-D.jpg','DrSrinivasulu-Mukta','','M CH Surgical Oncology','','',17,1,'2023-03-23 11:06:28','2023-08-04 11:09:15');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (23,'Dr. Annie Q. Hasan','Female','32+ years','Hyderabad','10AM - 5PM','Onco-Genetic Counselling','Supportive Care Specialist','Dr. Annie Q. Hasan1687240904-Dr. Anniee.jpg','annie-q-hasan','','PHD Genetics','','',19,1,'2023-03-23 11:06:28','2023-07-04 15:18:03');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (25,'Dr. Rajendar Byshetty','Male','8+ years','Hyderabad','10AM-5PM','Surgical Oncology','Consultant','Dr. Rajendar Byshetty1687240609-Dr. Rajendar Byshetty.jpg','rajendar-byshetty','Consultant & Surgical Oncology','MBBS , MS (JIPMER),\r\nDNB,MCh , (AIIMS) FMAS','','',13,1,'2023-04-07 14:25:15','2023-08-04 11:07:31');
INSERT INTO `` (`dr_id`,`dr_name`,`gender`,`experience`,`location`,`timings`,`expertise`,`role`,`image`,`ip_link`,`specialities`,`education`,`research_interests`,`extra_info`,`sort_order`,`status`,`created_on`,`updated_on`) VALUES (26,'Dr. Vinay Mamidala','Male','6+ years','Hyderabad','9:30 Am - 6:00 Pm','Surgical Oncology','Consultant','Dr. Vinay Mamidala1687240621-Dr. Vinay Mamidala.jpg','dr_vinay_mamidala','','FMAS , FARIS, M. Ch - 2023 , Ms  MBBS','','',12,1,'2023-06-13 17:20:32','2023-08-04 11:07:21');
